In [1]:
# Two simple ways to create an array

import numpy as np

a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [3]:
L= range(10000000)

%timeit [i**2 for i in L]

4.13 s ± 276 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
a=np.arange(10000000)
%timeit a**2

30.6 ms ± 6.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# Creating Arrays 

In [5]:
#1D

a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [6]:
a.ndim

1

In [7]:
a.shape

(4,)

In [8]:
len(a)

4

In [9]:
# 2 Dimensional Array

b= np.array([[1,2,3,4,5,6], [9,8,7,6,5,4]])
print(b)

[[1 2 3 4 5 6]
 [9 8 7 6 5 4]]


In [10]:
b.ndim

2

In [11]:
b.shape

(2, 6)

In [12]:
len(b) # return the size of the first dimension

2

In [13]:
c=np.array ([[[0,1],[1,2]],[[3,4],[5,6]]])

In [14]:
print (c)

[[[0 1]
  [1 2]]

 [[3 4]
  [5 6]]]


In [15]:
c.ndim

3

In [16]:
c.shape

(2, 2, 2)

In [17]:
len(c)


2

In [18]:
#2D array is called matrix 1D array is called as Vector
# ND is called Tensor

In [19]:
# Functions for creating arrays

In [20]:
a=np.arange(5)
print(a)

[0 1 2 3 4]


In [21]:
b=np.arange(0,10,6)  # start size, end size and step size
print(b)

[0 6]


In [22]:
# common arrays

In [23]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# using linspace
# this includes start and end size of the number as well

a=np.linspace(0,1,6)
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [25]:
b=np.linspace(0,10,6) 
print(b)

[ 0.  2.  4.  6.  8. 10.]


In [26]:
np.eye(3)  # diagonal of a matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
# create arrays using diag function

In [30]:
a=np.diag([1,2,3,4]) # to have these elements in the diagonal of a matrix
print(a)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [31]:
np.diag(a) # to see what is the diagonal element

array([1, 2, 3, 4])

In [32]:
# to print the random elements and it varies everytime as it is a random numbers
a=np.random.rand(4)
print(a)

[0.70967685 0.1936952  0.47068455 0.17688774]


In [33]:
# Array data types

In [34]:
a=np.arange(4)

In [35]:
type(a)
a.dtype

dtype('int32')

In [36]:
a=np.arange(12 , dtype='float64')  # to set the datatype we want
print(a)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


# Indexing and slicing in Python

Indexing is nothing but the items of the array can be accessed and assigned to the same way as other python sequences

In [37]:
a=np.arange(10)

In [38]:
print(a[5]) # accessiing the 5th index of the array

5


In [39]:
# For multiple dimensional arrays , indiex are tuples or integers

a=np.diag([1,2,3])
print(a)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [40]:
print(a[2,2])

3


In [41]:
# assigning a value

a[2,1]=5

In [42]:
print(a)

[[1 0 0]
 [0 2 0]
 [0 5 3]]


# Slicing

In [43]:
a=np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [44]:
a[1:10:2]

array([1, 3, 5, 7, 9])

In [45]:
# we can also combine assignment and slicing

In [51]:
a=np.arange(10)
a[:5]=10
print(a)

[10 10 10 10 10  5  6  7  8  9]


In [54]:
a=-np.arange(19)
print(a)

[  0  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15 -16 -17
 -18]


In [55]:
b=np.random.randint(1,20,19)
print(b)

[17  1  9 19 12 12  7  8 17 13  2 17 16  1  2  5  2  5 14]
